// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package handler

import (
	"net/http"

	device "github/ikun2021/bestpractice/app/user/api/internal/handler/device"
	social "github/ikun2021/bestpractice/app/user/api/internal/handler/social"
	"github/ikun2021/bestpractice/app/user/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/device/info",
				Handler: device.GetDeviceInfoHandler(serverCtx),
			},
		},
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/post/info",
				Handler: social.GetPostInfoHandler(serverCtx),
			},
		},
	)
}
