// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: user.proto

package server

import (
	"context"

	"github/ikun2021/bestpractice/app/user/rpc/internal/logic/socialservice"
	"github/ikun2021/bestpractice/app/user/rpc/internal/svc"
	"github/ikun2021/bestpractice/pb/userpb"
)

type SocialServiceServer struct {
	svcCtx *svc.ServiceContext
	userpb.UnimplementedSocialServiceServer
}

func NewSocialServiceServer(svcCtx *svc.ServiceContext) *SocialServiceServer {
	return &SocialServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *SocialServiceServer) GetPostInfo(ctx context.Context, in *userpb.GetPostInfoReq) (*userpb.GetPostInfoResp, error) {
	l := socialservicelogic.NewGetPostInfoLogic(ctx, s.svcCtx)
	return l.GetPostInfo(in)
}
