// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: user.proto

package server

import (
	"context"

	"github/ikun2021/bestpractice/app/user/cmd/rpc/internal/logic/deviceservice"
	"github/ikun2021/bestpractice/app/user/cmd/rpc/internal/svc"
	"github/ikun2021/bestpractice/pb/userpb"
)

type DeviceServiceServer struct {
	svcCtx *svc.ServiceContext
	userpb.UnimplementedDeviceServiceServer
}

func NewDeviceServiceServer(svcCtx *svc.ServiceContext) *DeviceServiceServer {
	return &DeviceServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *DeviceServiceServer) GetDeviceInfo(ctx context.Context, in *userpb.GetDeviceInfoReq) (*userpb.GetDeviceInfoResp, error) {
	l := deviceservicelogic.NewGetDeviceInfoLogic(ctx, s.svcCtx)
	return l.GetDeviceInfo(in)
}
