// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/account/getAccountInfo": {
            "get": {
                "security": [
                    {
                        "Account": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "GetAccountInfo"
                ],
                "summary": "获取账号信息",
                "parameters": [
                    {
                        "type": "string",
                        "name": "accountId",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "账号信息",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/account.GetAccountInfoResp"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "account.GetAccountInfoResp": {
            "type": "object",
            "properties": {
                "accountId": {
                    "type": "string"
                },
                "accountName": {
                    "type": "string"
                }
            }
        }
    },
    "tags": [
        {
            "name": "Base"
        },
        {
            "description": "用户",
            "name": "SysUser"
        }
    ]
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "v2.7.9",
	Host:             "",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "AccountApi接口",
	Description:      "AccountApi接口",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
