// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type GetDeviceInfoReq struct {
	Id string `form:"id"`
}

type GetDeviceInfoResp struct {
	Name     string `json:"name"`
	Email    string `json:"email"`
	Password string `json:"password"`
}

type GetPostInfoReq struct {
	Id string `form:"id"`
}

type GetPostInfoResp struct {
	Name     string `json:"name"`
	Email    string `json:"email"`
	Password string `json:"password"`
}
